name: Hourly Playlist Update

on:
  schedule:
    - cron: '0 * * * *'  # Runs exactly at the start of every hour
  workflow_dispatch:      # Allows you to click "Run workflow" manually

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: curl

      - name: Fetch Playlists
        run: php update.php

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          # This line checks if there are changes. If no changes, it won't error out.
          git diff --quiet && git diff --staged --quiet || (git commit -m "Hourly Update: $(date +'%Y-%m-%d %H:%M:%S')" && git push)
